### ISSUE TITLE
Grid broken in android browser

### ISSUE THREAD

**Issue by slavanga** [colourgarden/avalanche#2]
See: http://codepen.io/stowball/details/LsICH

**Comment by colourgarden** [comment]
Thanks for raising. Testing with Browserstack, this bug appears to have been fixed in Jellybean 4.3 which means that around only 30% of total Android devices are effected by it [1]. With up to 90% of Android devices having screens less than 600px in width [1], it's likely that the vast majority of Android users will be viewing a stacked single-column view so won't be visually effected.

The only bulletproof way to remove whitespace is to ensure there are no actual spaces in your markup. There are a number of ways of achieving this which are outlined [in this post](https://davidwalsh.name/remove-whitespace-inline-block). Many templating languages ([such as Twig](http://twig.sensiolabs.org/doc/tags/spaceless.html)) also have built-in methods of removing whitespace.

We'll all be using Flexbox soon enough anyway ;)

[1] - http://developer.android.com/about/dashboards/index.html

**Comment by slavanga** [comment]
I know the limitations and workarounds of inline-block. I guess it would be nice to have this documented for people who don't know.
