### ISSUE TITLE
Browser support and fallbacks

### ISSUE THREAD

**Issue by yumyo** [colourgarden/avalanche#3]
Hi,
Avalanche looks really promising, but apart from features and the small footprint it will be useful to know what is the actual browsers support and possible fallbacks.

**Comment by colourgarden** [comment]
All modern browsers are supported plus IE9+. If you require IE8 support then all that's needed is to add a pixel value for `font-size` onto `.grid__cell`. This is because IE8 doesn't support rem units. However, if you're using [autoprefixer](https://github.com/postcss/autoprefixer) (which you totally should be) then this will be handled automatically as long as you define IE8 in your config.

I'm in the process of putting together some proper tests but I'll add a section for browser support to the README now. Thanks for the feedback.

Would there be any desire for an IE8 flag? There could be a boolean value in the settings; `$enable-ie8-support`, which would set this pixel value for you. The value could also be a variable set to `16px !default` making it easily override-able in your own Sass settings file.

I'd prefer we all went down the autoprefixer route but if there's demand for it then I'll consider it. With XP not dying any time soon, I know IE8 is an unfortunate reality for many.

**Comment by yumyo** [comment]
Thank you, Tom, really helpful and complete answer. I need to support IE8, but autoprefix is already part of my workflow. Probably the same goes for many of us in these days. Congrats for Avalanche I will definitely use it in my next project.
