### ISSUE TITLE
Is there an option for inserting a blank space between grid cells?

### ISSUE THREAD

**Issue by chocolata** [colourgarden/avalanche#38]
Hi, 

My design is based on a 12 column grid, and I had no issue of extending the divider to 12.
The only problem is that in my design, I sometimes have:

- A column of 8/12
- A space of 1/12
- A box of 3/12

My question is: does Avalanche support pushing a grid cell 1/12?

Thanks in advance.

**Comment by neutraltone** [comment]
This something that I have been looking for. I've resorted to using flex for the time being and just using the `1/2` factional width classes in conjunction with `justify-content: space-between;`, it's not ideal and somewhat messy but it works for my current use case.

Harry Roberts has integrated such features in his simlar grid system (https://github.com/csswizardry/csswizardry-grids/blob/master/csswizardry-grids.scss#L472) but it doesn't look trivial to implement into Avalanche.

**Comment by colourgarden** [comment]
Hi @maartenmachiels. Avalanche doesn't have push/pull classes so this isn't possible out of the box. There's a couple of reasons for this:

- Push/pull classes produce a huge amount of unwanted CSS. The idea behind Avalanche is to create just the classes you need and nothing more - push/pull classes go against this philosophy because (without a tremendous amount of config) you have to spit out push/pull classes for all sizes at all breakpoints = hundreds of selectors
- Avalanche thinks of grids as fractions or percentages of a container. There isn't the concept of pushing or pulling something 'one column'

Because Avalanche grids are `inline-block`, all you need to do to achieve addition space between a grid cell is increase the `padding-left` value of whichever cell you want to push across. I'd recommend adding a utility class to the `.grid__cell` and then setting a new `padding-left` value. 

`calc()` could be your friend here by doing something like `padding-left: calc($av-gutter + 25%)` if you wanted to push a cell over by 25% (haven't tested this).

@neutraltone Thanks for your input Tony. The next version of Avalanche will be based on Flexbox which will make this kind of thing much easier.

**Comment by chocolata** [comment]
Thank you for your answer. I understand. Will investigate the padding-left solution. Thanks a bunch and have a nice day.
