### ISSUE TITLE
grid 12 is not working at above 9/12

### ISSUE THREAD

**Issue by caksony** [colourgarden/avalanche#43]
need your help, grid 12 is not working at 2 digits like class 10/12 and 11/12
but 9 and below is working fine
exp:
<pre><code>        &lt;div class="grid"&gt;
          &lt;div class="1/12 grid__cell"&gt;
            &lt;div class="box"&gt;.1/12&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="11/12 grid__cell"&gt;
            &lt;div class="box"&gt;.1/12&lt;/div&gt;
          &lt;/div&gt;
       &lt;/div
        &lt;div class="grid"&gt;
          &lt;div class="2/12 grid__cell"&gt;
            &lt;div class="box"&gt;.2/12&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="110/12 grid__cell"&gt;
            &lt;div class="box"&gt;.10/12&lt;/div&gt;
          &lt;/div&gt;
       &lt;/div&gt;
</code></pre>
thanks

**Comment by colourgarden** [comment]
@caksony Hi there. This was previously reported and fixed in #18.

Your posted markup has a couple of errors which may be causing problems.
1. Incorrectly closed `</div` on line 8
2. Incorrect `110/12` class name on line 13

With these errors corrected, everything works as expected - https://codepen.io/anon/pen/WLJaBZ.

If you still have problems then please could you post your Avalanche settings as `10/12` and `11/12` widths are not enabled by default.
