### ISSUE TITLE
New SASS compiling issue

### ISSUE THREAD

**Issue by MVivid** [colourgarden/avalanche#44]
It seems that there is a new problem when compiling the scss.
When using the `fraction` the result of classes is: `.\3 6\/12 {`
Before it was: `\36\/12 {`
It means we can't use e.g. `<div class="6/12 grid__cell">`

Can you please check that?

**Comment by colourgarden** [comment]
@MVivid @osilayer8 Sorry for taking so long to reply on this issue. It appears that Sass now inserts a blank space after any escaped character. This obviously breaks the class naming construction in Avalanche. I've just published a release to fix this (1.3.1) by changing to attribute selectors rather than simple classes.

So your compiled CSS will now have classes such as `[class="1/2"]` rather than `.\31\/2`.

Attribute selectors have exactly the same specificity as class selectors.

Thanks for continuing to support Avalanche and keep an eye out for version 2 coming soon!
